[workspace]
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>"]
channels = ["conda-forge"]
name = "probabl_online_talk_skrub"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
convert-to-notebook = "bash -c 'for file in python_files/*.py; do jupytext --to notebook \"$file\" --output \"notebooks/$(basename \"$file\" .py).ipynb\"; done'"

[dependencies]
jupyterlab = ">=4.4.9,<5"
ipykernel = ">=7.0.1,<8"
jupytext = ">=1.18.1,<2"
scikit-learn = ">=1.7.2,<2"
pandas = ">=2.3.3,<3"
polars = ">=1.34.0,<2"
skrub = ">=0.6.2,<0.7"
pyarrow = ">=21.0.0,<22"
sentence-transformers = ">=5.1.1,<6"
ruff = ">=0.14.1,<0.15"
