[workspace]
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>"]
channels = ["conda-forge"]
name = "probabl_online_talk_skrub"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]
convert-to-notebook = "bash -c 'for file in python_files/*.py; do jupytext --to notebook \"$file\" --output \"notebooks/$(basename \"$file\" .py).ipynb\"; done'"

[dependencies]
# tools
jupyterlab = ">=4.4.9,<5"
ipykernel = ">=7.0.1,<8"
jupytext = ">=1.18.1,<2"
ruff = ">=0.14.1,<0.15"
# data science
scikit-learn = ">=1.7.2,<2"
pandas = ">=2.3.3,<3"
polars = ">=1.34.0,<2"
skrub = ">=0.6.2,<0.7"
pyarrow = ">=21.0.0,<22"
sentence-transformers = ">=5.1.1,<6"
seaborn = ">=0.13.0,<1"
plotly = ">=6.3.1,<7"

[activation]
scripts = ["activate_dot.sh"]  # required by `pydot`

[target.win-64.activation]
scripts = ["activate_dot.bat"]
